### ISSUE TITLE
Error no bower.json when building

### ISSUE THREAD

**Issue by tscibilia** [mdouchement/standardnotes#2]
I searched around and your docker implementation seems to be the easiest to get started, however, I'm getting an error on step 28/49 of the initial build:
```
Step 28/49 : RUN bower install --allow-root
 ---> Running in a569573b296f
bower                           ENOENT No bower.json present
The command '/bin/sh -c bower install --allow-root' returned a non-zero code: 1
```

I'm running ubuntu 18.04.3, with docker 19.03.2 on a proxmox server. I already have some other containers running (like traefik) so I modified the docker-compose to include some additional items (see here https://hastebin.com/ojidexadin.txt)

**Comment by mdouchement** [comment]
The dashboard has been dropped so there no longer needs of bower.
